pipeline {
    agent any
    tools {
        ant 'Ant'
    }
    stages {
        stage('Clean') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml clean"
            }
        }
        stage('Build') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml build"
            }
        }
        stage('Test') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml Debt_CalculationTest"
            }
        }
        stage('Junit reports') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml junitreport"
            }
        }
        stage('Mutation_Testing') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml pit"
            }
        }
        stage('Find_Bugs') 
        {
            steps 
            {
                sh "ant -f demo1/build.xml spotbugs"
            }
        }
    }
}
